server:
  port: 21038

spring:
  datasource:
    url: jdbc:h2:file:~/test
    username: roll
    password: tide
    driver-class-name: org.h2.Driver
#    tomcat.max-active: 1
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: false
    properties:
      hibernate:
        format-sql: false

##eureka stuff
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://18.219.59.193:8761/eureka}
#eureka.instance.preferIpAddress=true
#eureka.instance.hostname=ec2-18-217-226-63.us-east-2.compute.amazonaws.com

#Actuator needs update for Spring Boot 2.0

endpoints:
  actuator:
    enabled: true
    sensitive: false
  sensitive: false